### ISSUE TITLE
Additional Detections resource

### ISSUE THREAD

**Issue by mthcht** [jatrost/awesome-detection-rules#3]
I have projects that could further enrich your collection of detection rules:

## Splunk:
- https://github.com/mthcht/ThreatHunting-Keywords

## Sigma:
- https://github.com/mthcht/ThreatHunting-Keywords-sigma-rules

## Other:
- https://github.com/mthcht/awesome-lists

**Comment by jatrost** [comment]
Thanks @mthcht . I added all of these.

**Comment by mthcht** [comment]
@jatrost thanks, recently created yara rules here https://github.com/mthcht/ThreatHunting-Keywords-yara-rules if you find it interresting for your list

**Comment by jatrost** [comment]
Thank you.  I just added https://github.com/jatrost/awesome-detection-rules/commit/0b18f034e962b361d84210be6b8879422dd9c741
